version: '3'

services:
  mongo:
    image: mongo:3.6.5
    ports:
      - '27017:27017'
    logging:
      driver: none
    ulimits:
      memlock: 9223372036854775807
      nproc: 131072
      nofile: 100000
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - ./mongo-data:/data/db
