source:
  pixels:
    authorization-token: ${PIXELS_AUTH}
    video-resource: https://api.pexels.com/videos
    audio-resource:
  pixabay:
    authorization-token: ${PIXABAY_AUTH}
    video-resource: https://pixabay.com/api/videos
    audio-resource:
  search-try: ${VIDEO_SEARCH_TRY:50}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:127.0.0.1}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:vmaker}

